N_GRAPH_VERTICES = 30
N_ANTS = N_GRAPH_VERTICES // 3

RANDOM_SEED: int = 666
N_CYCLES: int = 100

MIN_K_PARTITE_GRAPH_SIZE = 5
MAX_K_PARTITE_GRAPH_SIZE = 10

PARAM_ALPHA = 2
PARAM_BETA = 5
PARAM_RHO = .7
